name: label-approved-pull-requests

on:
    pull_request_review:
        branches: [master]

jobs:
    labelWhenApproved:
        name: Label when approved

        runs-on: ubuntu-latest

        steps:
            - name: Label approved pull requests
              uses: pullreminders/label-when-approved-action@master

              env:
                  APPROVALS: "1"
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  ADD_LABEL: "approved"
